services:
  tcp-monitor:
    image: tcp-monitor
    build:
      context: .
    privileged: true
    tty: true
    network_mode: host
    volumes:
    - /sys/kernel/debug:/sys/kernel/debug:rw \
    - /lib/modules:/lib/modules:ro \
    - /usr/src:/usr/src:ro \
    - /etc/localtime:/etc/localtime:ro \
    pid: host
    command:
    - python
    - tcp_monitor.py
